### ISSUE TITLE
Difference among `conv2d`, `convolution`, and `_convolution`

### ISSUE THREAD

**Issue by XinDongol** [awwong1/torchprof#1]
Thanks for sharing such a useful tool to profile pytorch model. 

```
Module                        | Self CPU total | CPU total | CUDA total
------------------------------|----------------|-----------|-----------
AlexNet                       |                |           |
├── features                  |                |           |
│├── 0                        |                |           |
││├── conv2d                  |       15.740us |   1.956ms |    1.972ms
││├── convolution             |       12.000us |   1.940ms |    1.957ms
││├── _convolution            |       36.590us |   1.928ms |    1.946ms
││├── contiguous              |        6.600us |   6.600us |    6.464us
││└── cudnn_convolution       |        1.885ms |   1.885ms |    1.906ms
│├── 1                        |                |           |
││└── relu_                   |       68.880us |  68.880us |   69.632us
│├── 2                        |                |           |
││├── max_pool2d              |       15.330us |  85.639us |   84.992us
││└── max_pool2d_with_indices |       70.309us |  70.309us |   70.656us
│├── 3                        |                |           |
```

`conv2d`, `convolution`, and `_convolution` are at the same level in your example of AlexNet. What is the difference among `conv2d`, `convolution`, and `_convolution`?

**Comment by awwong1** [comment]
I'm happy to hear the package is useful to you.
These values are the [native c++ functions](https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native) that are called.

- [conv2d](https://github.com/pytorch/pytorch/blob/358e0d3d44f3e9824632c7f10f968f941648c2e2/aten/src/ATen/native/Convolution.cpp#L453)
- [convolution](https://github.com/pytorch/pytorch/blob/358e0d3d44f3e9824632c7f10f968f941648c2e2/aten/src/ATen/native/Convolution.cpp#L488)
- [_convolution](https://github.com/pytorch/pytorch/blob/358e0d3d44f3e9824632c7f10f968f941648c2e2/aten/src/ATen/native/Convolution.cpp#L498)
