### ISSUE TITLE
Why is it different between torchprof time and pytorch actual training time?

### ISSUE THREAD

**Issue by ghost** [awwong1/torchprof#10]
Thanks for sharing such a useful tool for profile pytorch model. But When I use it, I meet some problem. I train ResNet50 by pytorch in ImageNet dataset(batch size = 64), and a single iteration costs 0.782ms. However I use torchprof to profile ResNet50, I find layer1 costs 1.539s. I am confused. Output likes this:
 Module           | Self CPU total | CPU total | CUDA total | Occurrences                                                                                                                                                                               
-----------------|----------------|-----------|------------|------------                                                                                                                                                                               
ResNet           |                |           |            |                                                                                                                                                                                           
├── conv1        |                |           |            |                                                                                                                                                                                           
├── bn1          |                |           |            |                                                                                                                                                                                           
├── relu         |                |           |            |                                                                                                                                                                                           
├── maxpool      |                |           |            |                                                                                                                                                                                           
├── layer1       |      142.341ms | 786.225ms |     1.539s |           1

**Comment by awwong1** [comment]
Hello, if I understand your question, you are asking why time from a single iteration of training is different than what torchprof outputs?

It is because torchprof only measures forward passes. The operations that occur during the backward pass during training are not the same as the forward pass.

EDIT: Your forward pass time seems very high- is it possible you are training on a high performance GPU and profiling on a low power embedded GPU device?

**Comment by ghost** [comment]
There is only one GPU in my machine.

**Comment by ghost** [comment]
So, I think it is not key point to solve this problem.

**Comment by awwong1** [comment]
I am unable to replicate this problem. Can you share a minimal example of your profiling code?. 

```python
import torch    # 1.5.0
import torchvision  # 0.6.0
import torchprof    #1.1.1

model = torchvision.models.resnet50(pretrained=False).cuda()
x = torch.rand([1, 3, 244, 244]).cuda()

with torchprof.Profile(model, use_cuda=True, paths=[("ResNet", "layer1")]) as prof:
    out = model(x)

print(prof)
```
```text
Module           | Self CPU total | CPU total | CUDA total | Occurrences                                                             
-----------------|----------------|-----------|------------|------------                                                             
ResNet           |                |           |            |                                                                         
├── conv1        |                |           |            |                                                                         
├── bn1          |                |           |            |                                                                         
├── relu         |                |           |            |                                                                         
├── maxpool      |                |           |            |                                                                         
├── layer1       |        5.564ms |  16.248ms |   17.918ms |           1                                                             
│├── 0           |                |           |            |                                                                         
││├── conv1      |                |           |            |
...
```

**Comment by ghost** [comment]
code like this:
```
import torch
import torchvision
import torchprof

torch.backends.cudnn.enabled = False

model = torchvision.models.resnet50(pretrained=False).cuda()
x = torch.rand([64, 3, 224, 224]).cuda()

paths=[("ResNet", "layer1")]

with torchprof.Profile(model, use_cuda=True, paths=paths) as prof:
    model(x)

print(prof)
```

```
Module           | Self CPU total | CPU total | CUDA total | Occurrences
-----------------|----------------|-----------|------------|------------
ResNet           |                |           |            |            
├── conv1        |                |           |            |            
├── bn1          |                |           |            |            
├── relu         |                |           |            |            
├── maxpool      |                |           |            |            
├── layer1       |      275.050ms |    1.515s |     2.989s |           1
│├── 0           |                |           |            |            
││├── conv1      |                |           |            |            
││├── bn1        |                |           |            |            
││├── conv2      |                |           |            | 
```

**Comment by ghost** [comment]
torch version is 1.5.0
torchvision version is 0.6.0+cu101
torchprof version is 1.1.1
gpu: gtx1080ti
I think code is same, I am confused.

**Comment by awwong1** [comment]
I'm also confused :confused: 
Just to clarify: Backwards pass != Forward pass; Total time != `start_time - time()`.

It might be more helpful if you tell me how you are measuring the time for the backwards pass?

**Comment by ghost** [comment]
I use pytorch example/imagenet/main.py train ResNet50 model. I find forward pass costs 260ms, and backward costs 522ms in a single iteration.(batch size = 64), I modify code in example/imagenet/main.py. like this:
```
def train(train_loader, model, criterion, optimizer, epoch, args):
    batch_time = AverageMeter('Time', ':6.3f')
    data_time = AverageMeter('Data', ':6.3f')
    losses = AverageMeter('Loss', ':.4e')
    top1 = AverageMeter('Acc@1', ':6.2f')
    top5 = AverageMeter('Acc@5', ':6.2f')
    progress = ProgressMeter(
        len(train_loader),
        [batch_time, data_time, losses, top1, top5],
        prefix="Epoch: [{}]".format(epoch))

    # switch to train mode
    model.train()

    end = time.time()
    for i, (images, target) in enumerate(train_loader):
        # measure data loading time
        data_time.update(time.time() - end)

        if args.gpu is not None:
            images = images.cuda(args.gpu, non_blocking=True)
        target = target.cuda(args.gpu, non_blocking=True)

        # compute output
        output = model(images)
        loss = criterion(output, target)
        print(time.time() - end)

        # measure accuracy and record loss
        acc1, acc5 = accuracy(output, target, topk=(1, 5))
        losses.update(loss.item(), images.size(0))
        top1.update(acc1[0], images.size(0))
        top5.update(acc5[0], images.size(0))

        # compute gradient and do SGD step
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        # measure elapsed time
        batch_time.update(time.time() - end)
        end = time.time()

        if i % args.print_freq == 0:
            progress.display(i)
```

**Comment by ghost** [comment]
Can you replicate this problem by my code?

**Comment by awwong1** [comment]
I don't see any issues.
Note that `time.time() - end` gives you an indication of perceived time of the model, but [this is not the same as CUDA/CPU total time](https://github.com/awwong1/torchprof/issues/6#issuecomment-582120080).

EDIT: Also, torchprof cannot handle backward passes, so it is confusing to me why you are comparing the forward pass times to the backward pass times.
