### ISSUE TITLE
adding a summary line ?

### ISSUE THREAD

**Issue by tensorbuffer** [awwong1/torchprof#11]
Wondering if you can add a summary line at the output end? Basically I am comparing a few models, so I don't need to know how long each op takes but I want to know how long the whole model takes. I can add them myself but given there are many layers and ms/us conversion it's not quick.

**Comment by awwong1** [comment]
Hi @tensorbuffer, if you want to profile the whole model why not directly use the autograd profiler?
https://pytorch.org/docs/stable/autograd.html#profiler

You don't incur the overhead of recursively hooking into each of the layers (the intended functionality of this package). The autograd profiler is what I use behind the scenes anyways.

**Comment by tensorbuffer** [comment]
ok thanks.
