### ISSUE TITLE
Big difference between using TorchProf versus raw autograd profiler

### ISSUE THREAD

**Issue by tensorbuffer** [awwong1/torchprof#13]
Hi,
I ran both TorchProf and autograd profiler on CPU only to compare. For TorchProf I sum it manually of the CPU_total. For autograd profiler I export as chrome trace and opens it in chrome, select the whole range, and there's a summary of 'Wall Duration'. 
With standard mobilenetv2 they match up, the numbers are fairly close: 76ms versus 75.5ms.
With SuperGlue (https://github.com/magicleap/SuperGluePretrainedNetwork), the numbers differ a lot: 405ms (TorchProf) versus 527ms (autograd profiler). Wondering what could be the reason.

**Comment by awwong1** [comment]
Hi @tensorbuffer,

I can only speculate as the times will vary by architecture.
This package hooks into each layer separately.
Running the autograd profiler on the entire model, you do not have this additional overhead.

Model profiling is something that needs to be run multiple times, as there are no guarantees on the result stability.
It is impacted by other processes utilizing the CPU, the current system temperature, drivers, optimization levels, etc.

Perhaps running many different attempts with some randomization of inputs (at least 3 different forward passes per batch size) and do a statistical comparison of the results?
It is hard to comment on a ~100ms difference without more information.

**Comment by tensorbuffer** [comment]
Ok thanks. The numbers I quote are average of 50 runs.
