### ISSUE TITLE
torchprof breaks on PyTorch 1.8.0 because a function name changed

### ISSUE THREAD

**Issue by ant0nsc** [awwong1/torchprof#18]
In PyTorch 1.8.0, a method name in the `EventList` class changed: `populate_cpu_children` has been made private, now `_populate_cpu_children`. This change was made in [#46470](https://github.com/pytorch/pytorch/pull/46470/files#diff-8137a27af89ba1dbfa19eecc4b12036ea20d78cbb96d7b541a814e014646a087R72). 
This breaks `torchprof` with PyTorch 1.8.0. 

Happy to create a PR for that, but would love to hear from @awwong1 if you are happy with having torchprof tied to version 1.8.0 of PyTorch. Alternatively, could put in a check which of the two methods is present.

**Comment by ant0nsc** [comment]
Upon checking, it seems that the call to `_populate_cpu_children` is actually no longer needed. The method is called indirectly via `_build_tree`, which triggers at the end of the context manager.

**Comment by awwong1** [comment]
I've tried to make the library backwards compatible, but I'd be happy to review a PR from you! Admittedly I haven't touched DL in some time 😅

**Comment by ant0nsc** [comment]
@awwong1 can I have your review on #19 please?

**Comment by awwong1** [comment]
https://github.com/awwong1/torchprof/releases/tag/v1.3.3
