### ISSUE TITLE
Suggestion: run multiple times, average the testing times

### ISSUE THREAD

**Issue by iamhankai** [awwong1/torchprof#2]
We know that it's not stable to run only once. To obtain reliable results, I suggest to run multiple times, average the testing times.

**Comment by awwong1** [comment]
I considered this approach, but I'm not sure if this library should have opinionated result stability.

The number of times to run before the results are stable is not well defined.
The profiler returned values may not have normal distribution (varies on tensor inputs, model architecture), so averaging may not be appropriate.

Is the event lists dictionary not sufficient to calculate this? The values are lists of EventLists, meaning that you can see individual executions.

```python
model = torchvision.models.alexnet(pretrained=False)
x = torch.rand([1, 3, 224, 224])

with torchprof.Profile(model) as prof:
    model(x)
    model(x)

trace, event_lists_dict = prof.raw()
print(len(event_lists_dict[trace[2].path])) # this is equal to 2 
```

**Comment by awwong1** [comment]
I'm going to close this issue for the time being. This package should mimic the autograd profile as much as possible and not infer result stability.
