### ISSUE TITLE
Should children cpu/cuda total time be counted?

### ISSUE THREAD

**Issue by phuotran** [awwong1/torchprof#6]
Hello,

These lines will sum the cpu total times and cuda times for all events in the current path:
https://github.com/awwong1/torchprof/blob/ebca8a1c94e1430db221e51e45be41b18e6c515b/torchprof/profile.py#L144-L145

In AlexNet, for the path `('AlexNet', 'classifier', '0')`, `events` is
```
[<FunctionEvent id=0 cpu_time=39.981us cpu_start=22.671 cpu_end=62.652 cpu_children=[1] cuda_time=39.936us name=dropout thread=0 input_shapes=[]>,                                                     
 <FunctionEvent id=1 cpu_time=29.053us cpu_start=27.992 cpu_end=57.045 cpu_children=[] cuda_time=29.696us name=_fused_dropout thread=0 input_shapes=[]>]
```
where the function event with `id=1` is the child of the function event with `id=0`. I may misunderstood, but if the function event `id=1` is a child of function event `id=0`, isn't the total cpu/cuda time of the function event `id=1` already included in the total cpu/cuda time of the function event `id=0`? If so, this would mean that we should not sum over all events, but only over events that do not have any parents?

**Comment by awwong1** [comment]
Hi @phuotran, this is an interesting question that I hope I can clarify with this example. Short answer is you should look at the `self_cpu_time_total`, as it accommodates child events already. There is currently no functionality for `self_cuda_time_total`, you should emit the nvtx range and use nvvp instead (cpu_children does not apply to cuda).

----
Each module may be comprised of multiple [FunctionEvent](https://github.com/pytorch/pytorch/blob/e922826dda69c08acfe35ffc7c1d591c1eac0d7b/torch/autograd/profiler.py#L555)s, where nesting may occur.

A FunctionEvent's `self_cpu_time_total` property takes its `cpu_time_total` and subtracts the self times of its children (self time).

https://github.com/pytorch/pytorch/blob/e922826dda69c08acfe35ffc7c1d591c1eac0d7b/torch/autograd/profiler.py#L580-L583

A FunctionEvent's `cpu_time_total` is its Interval end time subtracted by start time (total time).

https://github.com/pytorch/pytorch/blob/e922826dda69c08acfe35ffc7c1d591c1eac0d7b/torch/autograd/profiler.py#L542-L548

On my laptop (cpu only), the `('AlexNet', 'classifier', '0')` has the following events (times rounded to three digits):
```text
id=0 name=dropout
  self_cpu_time_total=25.004us
  cpu_time_total=205.480us
  cpu_start=77.995 cpu_end=283.475
  cpu_children=[1, 3, 4, 5]
id=1 name=empty_like
  self_cpu_time_total=4.436us
  cpu_time_total=8.184us
  cpu_start=83.687 cpu_end=91.871
  cpu_children=[2]
id=2 name=empty
  self_cpu_time_total=3.748us
  cpu_time_total=3.748us
  cpu_start=87.898 cpu_end=91.646
  cpu_children=[]
id=3 name=bernoulli_
  self_cpu_time_total=95.876us
  cpu_time_total=95.876us
  cpu_start=97.447 cpu_end=193.323
  cpu_children=[]
id=4 name=div_
  self_cpu_time_total=54.07us
  cpu_time_total=54.070us
  cpu_start=198.367 cpu_end=252.437
  cpu_children=[]
id=5 name=mul
  self_cpu_time_total=22.346us
  cpu_time_total=22.346us
  cpu_start=258.967 cpu_end=281.313
  cpu_children=[]
```
The only event that does not have a parent is `id=0 name=dropout`.

```python
# 283.475 - 77.995 (id=0 end - start)
# equivalent to sum([e.self_cpu_time_total for e in events])
# sum of all function event self times
module.self_cpu_time_total = 205.48

# 205.480 + 8.184 + 3.748 + 95.876 + 54.070 + 22.346
# sum([e.cpu_time_total for e in events])
# sum of all function event total times
module.cpu_time_total = 389.704
```

The [definitions of self time and total time](https://software.intel.com/en-us/vtune-help-self-time-and-total-time) that I am using:

* **Self time** is the time spent in a particular program unit. 
* **Total time** is the accumulated time that a program unit incurs. For functions, Total time includes Self time of the function itself and Self time of all functions that were called from that function.

**Comment by phuotran** [comment]
Thanks @awwong1 for clarifying. I guess my confusion came from believing that `self_cpu_time_total` would be the self time of the module (so excludes the children's time), while it seems to be the total time (and includes the children's time).
